environment: production
chdir: /home/leito1232/Рабочий стол/uploader
pid: ~/"Рабочий стол"/uploader/tmp/thin.pid
rackup: ~/"Рабочий стол"/uploader/config.ru
log: ~/"Рабочий стол"/uploader/log/thin.log
max_conns: 1024
timeout: 30
max_persisten_conns: 512
daemonize: true
